site_name: site_manager_docs
repo_url: https://github.com/jan-ldwg/site_manager_server
edit_uri: https://github.com/jan-ldwg/site_manager_docs/tree/main/docs
site_description:
site_author: Jan Ludwig
copyright:

watch:
  - ./

theme:
  name: material

  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - content.links.external
    - navigation.instant
    - navigation.sections
    - content.action.edit
    - content.footnote.tooltips

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

#-------------site structure

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial:
      - Getting started: tutorial/gettingstarted.md
      - Basic concepts: tutorial/concepts.md
      - Wiring diagram: tutorial/wiringdiagram.md
      - Cable list: tutorial/cablelist.md
      - Device list: tutorial/devicelist.md
  - Library:
      - Overview: library/overview.md
      - Create templates: library/create.md
      - Contribute: library/contribute.md
      #- Connectors: library/connectors.md
      #- Signals: library/signals.md
  #- Data Model:
  #- Device Types: datamodel/devicetype.md
  #- Devices: datamodel/devices.md
  - Release Notes: releasenotes.md
  - API:
      - Overview: api/overview.md
      - /devices: api/devices.md
      - /devices/{deviceId}: api/devices_deviceId.md
      - /ports/{portId}: api/ports_portId.md
      - /modules: api/modules.md
      - /modules/{moduleId}: api/modules_moduleId.md
      - /cables: api/cables.md
      - /cables/{cableId}: api/cables_cableId.md
      - /sites: api/sites.md
      - /sites/{siteId}: api/sites_siteId.md
      - /buildings: api/buildings.md
      - /buildings/{buildingId}: api/buildings_buildingId.md
      - /rooms: api/rooms.md
      - /rooms/{roomId}: api/rooms_roomId.md
      - /racks: api/racks.md
      - /racks/{rackId}: api/racks_rackId.md
      - /devicetypes: api/devicetypes.md
      - /devicetypes/{deviceTypeId}: api/devicetypes_deviceTypeId.md
      #- /moduleTypes: api/moduleTypes.md
      #- /moduleSlotsTypes: api/moduleSlotsTypes.md
      #- /portTypes: api/portTypes.md
      #- /signalTypes: api/signalTypes.md
      #- /connectors: api/connectors.md
      - /manufacturers: api/manufacturers.md
      - /manufacturers/{manufacturerId}: api/manufacturers_manufacturerId.md
